api: yes
apiAddress: 127.0.0.1:9997

rtspAddress: :8554
hlsAddress: :8888

pathDefaults:
  record: yes
  recordFormat: fmp4
  recordPath: /recordings/%path/%Y%m%d_%H%M%S-%f
  recordSegmentDuration: 10m

paths:
  cam: {}
