server {
    listen 80;

    location /static/ {
        alias /static/;
        expires 1h;
    }

    location /live/ {
        proxy_pass         http://mediamtx:8888/;
        proxy_buffering    off;
        proxy_cache        off;
        proxy_read_timeout 3600s;
    }

    location /recordings/ {
        alias /recordings/;
        add_header Content-Disposition 'inline';
    }

    # ESP32 webhooky — jen z lokální sítě a docker sítě
    location ~ ^/(motion|idle)$ {
        allow 192.168.1.0/24;
        allow 172.16.0.0/12;
        allow 127.0.0.1;
        deny all;
        proxy_pass http://cam-app:5000;
    }

    location / {
        proxy_pass       http://cam-app:5000;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
