services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "8888:8888"
    volumes:
      - ./docker/mediamtx.yml:/mediamtx.yml:ro
      - ./recordings:/recordings

  cam-app:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MEDIAMTX_HOST=mediamtx
      - RECS_DIR=/recordings
    volumes:
      - ./recordings:/recordings:ro
      - ./config.py:/app/config.py:ro
    depends_on:
      - mediamtx
